### ISSUE TITLE
will support iOS 11 ?

### ISSUE THREAD

**Issue by kingsword** [mringwal/hid-support#3]

**Comment by mringwal** [comment]
don't have an iOS 11 JB setup. does hid-support stopped working on iOS 11? if not, how far did you get?

**Comment by kingsword** [comment]
Sorry~ I made a command line tool with hid-support to simulate touch but I got 'killed: 9', I thought there's something wrong with it.But after I read your reply,  I run a tweak to simulate touch, it's still working~
Thanks~

**Comment by mringwal** [comment]
no problem. please provide full info when reporting issues :)
