### ISSUE TITLE
hid_support_send_message cannot find server ch.ringwald.hidsupport

### ISSUE THREAD

**Issue by laoyur** [mringwal/hid-support#5]
I got the error while trying to use hid-support(1.3.1-1) which was installed in cydia:
```
hid_support_send_message cannot find server ch.ringwald.hidsupport
```

I checked the code: 
https://github.com/mringwal/hid-support/blob/master/hidspringboard/Tweak.xm#L875

```
    if (!cfmessageportexposelocal);  // <--- NOTE the ; symbol
    cfmessageportexposelocal(local);
```
`cfmessageportexposelocal` seems never get called, could you please rebuild a new version ?
It is a hard work for me to build your project myself.
Many thanks !

**Comment by laoyur** [comment]
oh, my fault, the unexpected `;` is not the problem as the `cfmessageportexposelocal(local);` will always get called.

I can confirm `librocketbootstrap` has already been installed,
could you please help me figure out the problem ?

iOS 10.3.3

**Comment by mringwal** [comment]
in what context do you use the library? 
as far as I know, it works on 10.x.
did you try the hidsupporttest that is part of the repo (and probably installed as well)?

**Comment by laoyur** [comment]
@mringwal Hi, it might be the problem of rocketbootstrap

```
hid_support_message_port = rocketbootstrap_cfmessageportcreateremote(NULL, CFSTR(HID_SUPPORT_PORT_NAME));
```
I always get hid_support_message_port == 0
maybe I will try to replace rocketbootstrap with CPDistributedMessagingCenter if I have time later to test.
thanks for your reply.

**Comment by mringwal** [comment]
well. some iOS versions before, it CFMessagePorts worked without rocketbootstrap. Then, Apple added strong filters to prevent  it. Finally, rocketbootstrap worked its magic to allow connection again. I don't think it's possible without rocketbootstrap.

**Comment by laoyur** [comment]
@mringwal yes, I've heard a lot about what does rocketbootstrap do.
but, the very odd thing is, in my test, CPDistributedMessagingCenter works great without rocketbootstrap installed, I don't know why, it just works.

Device: iPhone SE, OS: 10.3.3, doubleh3lix jailbark
