### ISSUE TITLE
How to use Touch API ?

### ISSUE THREAD

**Issue by laoyur** [mringwal/hid-support#6]
hi,
```
    int hid_inject_mouse_rel_move(uint8_t buttons, float dx, float dy);
    int hid_inject_mouse_abs_move(uint8_t buttons, float ax, float ay);
```

the mouse related apis confuse me a lot, I cannot find any info about the `uint8_t buttons` in source code. and the sample code in `hidsupporttest` does not help at all.
Could you please provide more sample code ? I want to simulate touch and drag event.

another question:
https://github.com/mringwal/hid-support/blob/master/hidspringboard/Tweak.xm#L395
```
IOHIDEventRef parent = IOHIDEventCreateDigitizerEvent(kCFAllocatorDefault, mach_absolute_time(), kIOHIDDigitizerTransducerTypeHand, 1<<22, 1, parent_flags, 0, xf, yf, 0, 0, 0, 0, 0, 0);
```
Note the `kIOHIDDigitizerTransducerTypeHand`, but in another project https://github.com/iolate/SimulateTouch/blob/master/SimulateTouch.mm#L184
it use `kIOHIDTransducerTypeHand == 3` for iOS 7+

**Comment by mringwal** [comment]
the mouse api delivers touch events. buttons = 1 => touch. To simulate a drag, you simulate touching the screen along a path: e.g. drag from 100,100 to 200,200, you hid_inject_mouse_abs_move with buttons = 1 e.g. at 100,100 - 120,120 -140,140 - ... - 200,200, and finally you call it once more with buttons = 0.

IOHIDEventCreateDigitizerEvent: as everything is reverse engineered, you're guess is as good as mine. Usually people log the call from the system or play around. If it works, the values are kept without fully understanding them. iolate got his code working with different value, I found mine.

**Comment by sliverblack** [comment]
hi @mringwal
It's not work int IOS 11. please help me

**Comment by mringwal** [comment]
Feel free to create a new issue for hid-support on iOS 11.

hid-support uses CFMessagePorts for communication from the libhidsuport to the server inside backboardd. I guess either creating and exposing the message port via rocket bootstrap  fails or your tweak/app cannot connect to it. 

Sorry, I'm not active on iOS JB and cannot actively help  you here.
