### ISSUE TITLE
Don't support landscape?

### ISSUE THREAD

**Issue by SjonC** [mringwal/hid-support#8]
Don't support landscape?
When I use iPhone6 iOS 9.3.3 landscape click in the right position, vertical screen when no problem.

**Comment by mringwal** [comment]
hid-support rotates the coordinates depending on the device rotation. What is your setup?

**Comment by SjonC** [comment]
Thank you very much, is I write wrong

**Comment by SjonC** [comment]
Thank you very much, is I write wrong.
